In [1]:
pip install vaderSentiment

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install nltk

Note: you may need to restart the kernel to use updated packages.


In [3]:
import pandas as pd
import numpy as np
from textblob import TextBlob
import re
from nltk.sentiment import SentimentIntensityAnalyzer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [4]:
Alle6Test = pd.read_csv(r"/Users/joakimlarsen/Documents/MasterOppgave/TestAlle6.csv")

In [5]:
Alle6Test.shape

(1141, 14)

In [6]:
Alle6Test.head(3)

X    Open         Low         High        Date        Close   Volume  \
0  4996  1680.0  1641.50000  1692.119995  2018-12-13  1658.380005  5271300   
1  4954  1638.0  1585.00000  1642.569946  2018-12-14  1591.910034  6367200   
2  4987  1566.0  1505.01001  1576.130005  2018-12-17  1520.910034  8829800   

   Subjectivity  Polarity  Compound  Negative  Neutral  Positive  Label  
0      0.570661  0.230603    0.9882     0.053    0.815     0.132      0  
1      0.488820  0.162102    0.9979     0.042    0.782     0.176      0  
2      0.436101  0.173839    0.9964     0.040    0.800     0.159      0

In [7]:
Alle6Train = pd.read_csv(r"/Users/joakimlarsen/Documents/MasterOppgave/TrainAlle6.csv")

In [8]:
Alle6Train.shape

(6385, 14)

In [9]:
Alle6Train.head(3)

X        Open         Low        High        Date       Close    Volume  \
0  6463  122.930000  119.419998  124.260002  2009-10-27  122.070000  20304200   
1  6460  138.399994  135.279999  138.399994  2009-12-30  136.490005   6913200   
2  6478  127.260002  125.000000  128.149994  2010-01-21  126.620003   9970600   

   Subjectivity  Polarity  Compound  Negative  Neutral  Positive  Label  
0      0.510827  0.007888   -0.9112     0.141    0.743     0.116      0  
1      0.474264  0.146567    0.9924     0.033    0.834     0.133      0  
2      0.474021  0.164377    0.9989     0.066    0.750     0.184      0

In [10]:
#Create a list of column to keep
keep_columns1 = ["Open", "Low", "High", "Volume","Close", "Subjectivity", "Polarity", "Compound", "Negative", "Neutral", "Positive", "Label"]
df1 = Alle6Test[keep_columns1]
df1

Open          Low         High    Volume        Close  \
0     1680.000000  1641.500000  1692.119995   5271300  1658.380005   
1     1638.000000  1585.000000  1642.569946   6367200  1591.910034   
2     1566.000000  1505.010010  1576.130005   8829800  1520.910034   
3     1540.000000  1523.010010  1567.550049   6523000  1551.479980   
4     1543.050049  1483.180054  1584.530029   8792200  1495.079956   
...           ...          ...          ...       ...          ...   
1136    44.402000    43.520000    44.644001  38971500    44.166000   
1137    44.560001    43.644001    45.080002  32795000    44.430000   
1138    43.993999    42.200001    44.234001  42693000    42.279999   
1139    42.720001    42.307999    43.004002  25259500    43.000000   
1140    42.737999    42.462002    43.450001  16127500    43.118000   

      Subjectivity  Polarity  Compound  Negative  Neutral  Positive  Label  
0         0.570661  0.230603    0.9882     0.053    0.815     0.132      0  
1         0.488820  0.162102    0.9979     0.042    0.782     0.176      0  
2         0.436101  0.173839    0.9964     0.040    0.800     0.159      0  
3         0.479953  0.195635    0.9401     0.088    0.752     0.160      1  
4         0.323829  0.035114   -0.8860     0.123    0.786     0.091      0  
...            ...       ...       ...       ...      ...       ...    ...  
1136      0.427273  0.268182   -0.7650     0.167    0.833     0.000      0  
1137      0.405637  0.059591    0.9954     0.053    0.806     0.141      0  
1138      0.463922  0.001857    0.9678     0.056    0.854     0.089      0  
1139      0.426042  0.218750   -0.6124     0.044    0.947     0.009      1  
1140      0.454072  0.102247    0.9994     0.036    0.865     0.100      1  

[1141 rows x 12 columns]

In [11]:
#Create the feature data set
X = df1
X = np.array(X.drop(["Label"], 1))

#Create the target data set
y = np.array(df1["Label"])

/var/folders/m7/01kjn8yx6d3_tjkcr1dkd9g80000gn/T/ipykernel_14770/3997290794.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  X = np.array(X.drop(["Label"], 1))


In [12]:
X

array([[1.68000000e+03, 1.64150000e+03, 1.69212000e+03, ...,
        5.30000000e-02, 8.15000000e-01, 1.32000000e-01],
       [1.63800000e+03, 1.58500000e+03, 1.64256995e+03, ...,
        4.20000000e-02, 7.82000000e-01, 1.76000000e-01],
       [1.56600000e+03, 1.50501001e+03, 1.57613000e+03, ...,
        4.00000000e-02, 8.00000000e-01, 1.59000000e-01],
       ...,
       [4.39939995e+01, 4.22000008e+01, 4.42340012e+01, ...,
        5.60000000e-02, 8.54000000e-01, 8.90000000e-02],
       [4.27200012e+01, 4.23079987e+01, 4.30040016e+01, ...,
        4.40000000e-02, 9.47000000e-01, 9.00000000e-03],
       [4.27379990e+01, 4.24620018e+01, 4.34500008e+01, ...,
        3.60000000e-02, 8.65000000e-01, 1.00000000e-01]])

In [13]:
y

array([0, 0, 0, ..., 0, 1, 1])

In [14]:
x_test = X

In [15]:
len(x_test)

1141

In [16]:
y_test = y

In [17]:
len(y_test)

1141

In [18]:
#Create a list of column to keep
keep_columns2 = ["Open", "Low", "High", "Volume", "Close", "Subjectivity", "Polarity", "Compound", "Negative", "Neutral", "Positive", "Label"]
df2 = Alle6Train[keep_columns2]
df2

Open         Low        High     Volume       Close  Subjectivity  \
0     122.930000  119.419998  124.260002   20304200  122.070000      0.510827   
1     138.399994  135.279999  138.399994    6913200  136.490005      0.474264   
2     127.260002  125.000000  128.149994    9970600  126.620003      0.474021   
3     124.430000  122.800003  127.199997   27293100  126.029999      0.480021   
4     129.770004  124.139999  131.850006   29471300  125.410004      0.559074   
...          ...         ...         ...        ...         ...           ...   
6380   60.382000   60.222000   62.778000   39216000   61.916000      0.512043   
6381   62.580002   61.382000   62.992001   42545500   61.504002      0.456944   
6382   54.051998   52.112000   55.599998  168248500   52.953999      0.481553   
6383   61.153999   60.209999   62.287998  108888000   62.139999      0.421098   
6384   62.790001   59.830002   63.368000   58717500   60.203999      0.357611   

      Polarity  Compound  Negative  Neutral  Positive  Label  
0     0.007888   -0.9112     0.141    0.743     0.116      0  
1     0.146567    0.9924     0.033    0.834     0.133      0  
2     0.164377    0.9989     0.066    0.750     0.184      0  
3     0.097400    0.9993     0.040    0.782     0.177      1  
4     0.113064    0.9935     0.062    0.767     0.172      0  
...        ...       ...       ...      ...       ...    ...  
6380  0.151823    0.9547     0.061    0.842     0.097      1  
6381  0.083714    0.8910     0.067    0.826     0.107      0  
6382  0.166611    0.6167     0.049    0.887     0.065      0  
6383  0.091727    0.9851     0.056    0.785     0.159      1  
6384  0.007640    0.8360     0.062    0.848     0.090      0  

[6385 rows x 12 columns]

In [19]:
#Create the feature data set
X1 = df2
X1 = np.array(X1.drop(["Label"], 1))

#Create the target data set
y1 = np.array(df2["Label"])

/var/folders/m7/01kjn8yx6d3_tjkcr1dkd9g80000gn/T/ipykernel_14770/791745654.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  X1 = np.array(X1.drop(["Label"], 1))


In [20]:
X1

array([[1.22930000e+02, 1.19419998e+02, 1.24260002e+02, ...,
        1.41000000e-01, 7.43000000e-01, 1.16000000e-01],
       [1.38399994e+02, 1.35279999e+02, 1.38399994e+02, ...,
        3.30000000e-02, 8.34000000e-01, 1.33000000e-01],
       [1.27260002e+02, 1.25000000e+02, 1.28149994e+02, ...,
        6.60000000e-02, 7.50000000e-01, 1.84000000e-01],
       ...,
       [5.40519981e+01, 5.21119995e+01, 5.55999985e+01, ...,
        4.90000000e-02, 8.87000000e-01, 6.50000000e-02],
       [6.11539993e+01, 6.02099991e+01, 6.22879982e+01, ...,
        5.60000000e-02, 7.85000000e-01, 1.59000000e-01],
       [6.27900009e+01, 5.98300018e+01, 6.33680000e+01, ...,
        6.20000000e-02, 8.48000000e-01, 9.00000000e-02]])

In [21]:
y1

array([0, 0, 0, ..., 0, 1, 0])

In [22]:
x_train = X1

In [23]:
len(x_train)

6385

In [24]:
y_train = y1

In [25]:
len(y_train)

6385

In [26]:
#Create and train the model
model = LinearDiscriminantAnalysis().fit(x_train, y_train)

In [27]:
#Show the models predictions
predictions = model.predict(x_test)
predictions

array([0, 0, 0, ..., 0, 0, 1])

In [28]:
y_test

array([0, 0, 0, ..., 0, 1, 1])

In [29]:
#Show the model metrics
print( classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.84      0.88      0.86       561
           1       0.88      0.84      0.86       580

    accuracy                           0.86      1141
   macro avg       0.86      0.86      0.86      1141
weighted avg       0.86      0.86      0.86      1141



In [30]:
#Create and train the model (Naive Bayes)
from sklearn.naive_bayes import GaussianNB
modelNB = GaussianNB()

In [31]:
#Train the model
modelNB.fit(x_train, y_train)

GaussianNB()

In [32]:
#Accuracy for modellen
modelNB.score(x_test, y_test)

0.5144609991235758

In [39]:
predictions1 = modelNB.predict(x_test)
predictions1

array([1, 1, 1, ..., 1, 1, 1])

In [40]:
#Show the model metrics
print( classification_report(y_test, predictions1))

              precision    recall  f1-score   support

           0       0.67      0.02      0.05       561
           1       0.51      0.99      0.67       580

    accuracy                           0.51      1141
   macro avg       0.59      0.51      0.36      1141
weighted avg       0.59      0.51      0.37      1141



In [33]:
x_test[:10]

array([[ 1.68000000e+03,  1.64150000e+03,  1.69212000e+03,
         5.27130000e+06,  1.65838000e+03,  5.70661157e-01,
         2.30603109e-01,  9.88200000e-01,  5.30000000e-02,
         8.15000000e-01,  1.32000000e-01],
       [ 1.63800000e+03,  1.58500000e+03,  1.64256995e+03,
         6.36720000e+06,  1.59191003e+03,  4.88819856e-01,
         1.62102061e-01,  9.97900000e-01,  4.20000000e-02,
         7.82000000e-01,  1.76000000e-01],
       [ 1.56600000e+03,  1.50501001e+03,  1.57613000e+03,
         8.82980000e+06,  1.52091003e+03,  4.36101190e-01,
         1.73839286e-01,  9.96400000e-01,  4.00000000e-02,
         8.00000000e-01,  1.59000000e-01],
       [ 1.54000000e+03,  1.52301001e+03,  1.56755005e+03,
         6.52300000e+06,  1.55147998e+03,  4.79953476e-01,
         1.95634921e-01,  9.40100000e-01,  8.80000000e-02,
         7.52000000e-01,  1.60000000e-01],
       [ 1.54305005e+03,  1.48318005e+03,  1.58453003e+03,
         8.79220000e+06,  1.49507996e+03,  3.23828764e-01,
  

In [34]:
#Faktisk oppgang eller nedgang
y_test[:100]

array([0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1])

In [35]:
#Sjekker om vi modellen predikerer rett
modelNB.predict(x_test[:100])

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [36]:
#Sjekker sannsynligheten for oppgang og nedgang
Bayes = modelNB.predict_proba(x_test)

In [37]:
Bayes

array([[0.46809224, 0.53190776],
       [0.46796851, 0.53203149],
       [0.46768334, 0.53231666],
       ...,
       [0.46571863, 0.53428137],
       [0.46660136, 0.53339864],
       [0.46741355, 0.53258645]])

In [38]:
column_values = ["Nedgang", "Oppgang"]

df3 = pd.DataFrame(data = Bayes,
                  columns = column_values)

In [41]:
df3

Nedgang   Oppgang
0     0.468092  0.531908
1     0.467969  0.532031
2     0.467683  0.532317
3     0.467972  0.532028
4     0.467694  0.532306
...        ...       ...
1136  0.465833  0.534167
1137  0.466112  0.533888
1138  0.465719  0.534281
1139  0.466601  0.533399
1140  0.467414  0.532586

[1141 rows x 2 columns]

In [42]:
extracted_col = df3["Nedgang"]
extracted_col

0       0.468092
1       0.467969
2       0.467683
3       0.467972
4       0.467694
          ...   
1136    0.465833
1137    0.466112
1138    0.465719
1139    0.466601
1140    0.467414
Name: Nedgang, Length: 1141, dtype: float64

In [43]:
df1 = df1.join(extracted_col)
df1

Open          Low         High    Volume        Close  \
0     1680.000000  1641.500000  1692.119995   5271300  1658.380005   
1     1638.000000  1585.000000  1642.569946   6367200  1591.910034   
2     1566.000000  1505.010010  1576.130005   8829800  1520.910034   
3     1540.000000  1523.010010  1567.550049   6523000  1551.479980   
4     1543.050049  1483.180054  1584.530029   8792200  1495.079956   
...           ...          ...          ...       ...          ...   
1136    44.402000    43.520000    44.644001  38971500    44.166000   
1137    44.560001    43.644001    45.080002  32795000    44.430000   
1138    43.993999    42.200001    44.234001  42693000    42.279999   
1139    42.720001    42.307999    43.004002  25259500    43.000000   
1140    42.737999    42.462002    43.450001  16127500    43.118000   

      Subjectivity  Polarity  Compound  Negative  Neutral  Positive  Label  \
0         0.570661  0.230603    0.9882     0.053    0.815     0.132      0   
1         0.488820  0.162102    0.9979     0.042    0.782     0.176      0   
2         0.436101  0.173839    0.9964     0.040    0.800     0.159      0   
3         0.479953  0.195635    0.9401     0.088    0.752     0.160      1   
4         0.323829  0.035114   -0.8860     0.123    0.786     0.091      0   
...            ...       ...       ...       ...      ...       ...    ...   
1136      0.427273  0.268182   -0.7650     0.167    0.833     0.000      0   
1137      0.405637  0.059591    0.9954     0.053    0.806     0.141      0   
1138      0.463922  0.001857    0.9678     0.056    0.854     0.089      0   
1139      0.426042  0.218750   -0.6124     0.044    0.947     0.009      1   
1140      0.454072  0.102247    0.9994     0.036    0.865     0.100      1   

       Nedgang  
0     0.468092  
1     0.467969  
2     0.467683  
3     0.467972  
4     0.467694  
...        ...  
1136  0.465833  
1137  0.466112  
1138  0.465719  
1139  0.466601  
1140  0.467414  

[1141 rows x 13 columns]

In [44]:
extracted_col1 = df3["Oppgang"]
extracted_col1

0       0.531908
1       0.532031
2       0.532317
3       0.532028
4       0.532306
          ...   
1136    0.534167
1137    0.533888
1138    0.534281
1139    0.533399
1140    0.532586
Name: Oppgang, Length: 1141, dtype: float64

In [45]:
df1 = df1.join(extracted_col1)
df1

Open          Low         High    Volume        Close  \
0     1680.000000  1641.500000  1692.119995   5271300  1658.380005   
1     1638.000000  1585.000000  1642.569946   6367200  1591.910034   
2     1566.000000  1505.010010  1576.130005   8829800  1520.910034   
3     1540.000000  1523.010010  1567.550049   6523000  1551.479980   
4     1543.050049  1483.180054  1584.530029   8792200  1495.079956   
...           ...          ...          ...       ...          ...   
1136    44.402000    43.520000    44.644001  38971500    44.166000   
1137    44.560001    43.644001    45.080002  32795000    44.430000   
1138    43.993999    42.200001    44.234001  42693000    42.279999   
1139    42.720001    42.307999    43.004002  25259500    43.000000   
1140    42.737999    42.462002    43.450001  16127500    43.118000   

      Subjectivity  Polarity  Compound  Negative  Neutral  Positive  Label  \
0         0.570661  0.230603    0.9882     0.053    0.815     0.132      0   
1         0.488820  0.162102    0.9979     0.042    0.782     0.176      0   
2         0.436101  0.173839    0.9964     0.040    0.800     0.159      0   
3         0.479953  0.195635    0.9401     0.088    0.752     0.160      1   
4         0.323829  0.035114   -0.8860     0.123    0.786     0.091      0   
...            ...       ...       ...       ...      ...       ...    ...   
1136      0.427273  0.268182   -0.7650     0.167    0.833     0.000      0   
1137      0.405637  0.059591    0.9954     0.053    0.806     0.141      0   
1138      0.463922  0.001857    0.9678     0.056    0.854     0.089      0   
1139      0.426042  0.218750   -0.6124     0.044    0.947     0.009      1   
1140      0.454072  0.102247    0.9994     0.036    0.865     0.100      1   

       Nedgang   Oppgang  
0     0.468092  0.531908  
1     0.467969  0.532031  
2     0.467683  0.532317  
3     0.467972  0.532028  
4     0.467694  0.532306  
...        ...       ...  
1136  0.465833  0.534167  
1137  0.466112  0.533888  
1138  0.465719  0.534281  
1139  0.466601  0.533399  
1140  0.467414  0.532586  

[1141 rows x 14 columns]

In [46]:
df1.head(60)

Open          Low         High    Volume        Close  \
0   1680.000000  1641.500000  1692.119995   5271300  1658.380005   
1   1638.000000  1585.000000  1642.569946   6367200  1591.910034   
2   1566.000000  1505.010010  1576.130005   8829800  1520.910034   
3   1540.000000  1523.010010  1567.550049   6523000  1551.479980   
4   1543.050049  1483.180054  1584.530029   8792200  1495.079956   
5   1484.000000  1432.689941  1509.500000   9991800  1460.829956   
6   1464.989990  1363.959961  1480.000000  13640300  1377.449951   
7   1346.000000  1307.000000  1396.030029   7220000  1343.959961   
8   1368.890015  1363.010010  1473.160034  10411800  1470.900024   
9   1454.199951  1390.310059  1469.000000   9722000  1461.640015   
10  1473.349976  1449.000000  1513.469971   8829000  1478.020020   
11  1510.800049  1487.000000  1520.760010   6954500  1501.969971   
12  1465.199951  1460.930054  1553.359985   7983100  1539.130005   
13  1520.010010  1497.109985  1538.000000   6975600  1500.280029   
14  1530.000000  1518.310059  1594.000000   9182600  1575.390015   
15  1602.310059  1589.189941  1634.560059   7993200  1629.510010   
16  1664.689941  1616.609985  1676.609985   8881400  1656.579956   
17  1652.979980  1641.400024  1667.800049   6348800  1659.420044   
18  1641.010010  1621.619995  1663.250000   6507700  1656.219971   
19  1640.550049  1636.219971  1660.290039   4686200  1640.560059   
20  1615.000000  1595.150024  1648.199951   6005900  1617.209961   
21  1632.000000  1626.010010  1675.160034   5998500  1674.560059   
22  1684.219971  1675.880005  1705.000000   6366900  1683.780029   
23  1680.000000  1677.500000  1700.170044   4208900  1693.219971   
24  1712.000000  1691.540039  1716.199951   6020500  1696.199951   
25  1681.000000  1610.199951  1681.869995   6416800  1632.170044   
26  1656.000000  1612.000000  1657.430054   5225200  1640.020020   
27  1641.069946  1631.780029  1657.260010   4089900  1654.930054   
28  1670.500000  1661.609985  1683.479980   4945900  1670.569946   
29  1643.589966  1614.089966  1645.000000   4837700  1637.890015   
30  1631.270020  1590.719971  1632.380005   4632800  1593.880005   
31  1623.000000  1619.680054  1676.949951   5783800  1670.430054   
32  1692.849976  1679.079956  1736.410034  10910300  1718.729980   
33  1638.880005  1622.010010  1673.060059  11506200  1626.229980   
34  1623.000000  1613.500000  1649.630005   4929100  1633.310059   
35  1643.339966  1642.500000  1665.260010   4453100  1658.810059   
36  1670.750000  1633.339966  1672.260010   3939900  1640.260010   
37  1625.000000  1592.910034  1625.540039   4626600  1614.369995   
38  1600.979980  1586.000000  1609.290039   3317300  1591.000000   
39  1604.000000  1598.880005  1639.400024   4858600  1638.010010   
40  1647.000000  1637.109985  1656.380005   3560300  1640.000000   
41  1624.500000  1606.060059  1637.900024   4120500  1622.650024   
42  1627.859985  1604.500000  1628.910034   4343900  1607.949951   
43  1601.000000  1600.560059  1634.000000   3681700  1627.579956   
44  1630.000000  1610.119995  1634.930054   3337600  1622.099976   
45  1619.849976  1600.910034  1623.560059   3483400  1619.439941   
46  1623.500000  1621.170044  1634.939941   3096200  1631.560059   
47  1641.449951  1630.390015  1654.599976   3184500  1633.000000   
48  1625.979980  1616.130005  1639.989990   2665800  1636.400024   
49  1628.180054  1615.099976  1641.810059   3148800  1641.089966   
50  1635.250000  1633.829956  1651.770020   3025900  1639.829956   
51  1655.130005  1651.000000  1674.260010   4974900  1671.729980   
52  1685.000000  1674.359985  1709.430054   6167400  1696.170044   
53  1702.949951  1689.010010  1707.800049   3681500  1692.430054   
54  1695.969971  1668.280029  1697.750000   3996000  1668.949951   
55  1667.369995  1620.510010  1669.750000   4957000  1625.949951   
56  1604.010010  1586.569946  1622.719971   4667000  1620.800049   
57  1626.119995  1626.010010  1672.290039   3876400  1670.619995   

In [47]:
df1.to_csv("Alle6OppgangNedgangUnik")

In [48]:
df1.sort_values("Oppgang", ascending = True)

Open         Low        High     Volume       Close  Subjectivity  \
189    53.473684   52.628392   53.614162  384986800   52.718010      0.330929   
251    38.124593   36.367353   38.440557  382978400   36.634705      0.477962   
219    50.753743   49.755862   51.746775  365314800   50.252380      0.502851   
258    34.994134   34.512898   35.417039  365248800   34.559078      0.336233   
396    53.029591   51.775034   54.242494  277125600   52.201385      0.450944   
...          ...         ...         ...        ...         ...           ...   
1044   55.296001   54.877998   56.301998   51677500   55.248001      0.400000   
964    94.680000   93.919998   95.379997   49081300   94.599998      0.570000   
570   175.000000  161.009995  175.050003   56059600  164.149994      0.061111   
435   139.940002  139.740005  146.639999   50528300  146.220001      0.504172   
547   196.979996  192.119995  198.479996   54148800  193.259995      0.482286   

      Polarity  Compound  Negative  Neutral  Positive  Label   Nedgang  \
189   0.119610   -0.7906     0.065    0.895     0.039      0  0.623944   
251   0.107384    0.9721     0.049    0.840     0.111      0  0.622133   
219   0.024342    0.9863     0.000    0.883     0.117      0  0.606487   
258   0.206725    0.9779     0.037    0.788     0.175      0  0.606435   
396   0.165832    1.0000     0.021    0.842     0.137      0  0.539171   
...        ...       ...       ...      ...       ...    ...       ...   
1044 -0.100000    0.0000     0.000    1.000     0.000      0  0.465601   
964  -0.026667    0.2960     0.000    0.937     0.062      0  0.465596   
570   0.022222    0.2732     0.000    0.964     0.036      0  0.465590   
435   0.109668    0.9776     0.049    0.825     0.126      1  0.465570   
547   0.138750    0.9545     0.009    0.887     0.104      0  0.465560   

       Oppgang  
189   0.376056  
251   0.377867  
219   0.393513  
258   0.393565  
396   0.460829  
...        ...  
1044  0.534399  
964   0.534404  
570   0.534410  
435   0.534430  
547   0.534440  

[1141 rows x 14 columns]

In [49]:
df1.sort_values("Nedgang", ascending = True)

Open         Low        High     Volume       Close  Subjectivity  \
547   196.979996  192.119995  198.479996   54148800  193.259995      0.482286   
435   139.940002  139.740005  146.639999   50528300  146.220001      0.504172   
570   175.000000  161.009995  175.050003   56059600  164.149994      0.061111   
964    94.680000   93.919998   95.379997   49081300   94.599998      0.570000   
1044   55.296001   54.877998   56.301998   51677500   55.248001      0.400000   
...          ...         ...         ...        ...         ...           ...   
396    53.029591   51.775034   54.242494  277125600   52.201385      0.450944   
258    34.994134   34.512898   35.417039  365248800   34.559078      0.336233   
219    50.753743   49.755862   51.746775  365314800   50.252380      0.502851   
251    38.124593   36.367353   38.440557  382978400   36.634705      0.477962   
189    53.473684   52.628392   53.614162  384986800   52.718010      0.330929   

      Polarity  Compound  Negative  Neutral  Positive  Label   Nedgang  \
547   0.138750    0.9545     0.009    0.887     0.104      0  0.465560   
435   0.109668    0.9776     0.049    0.825     0.126      1  0.465570   
570   0.022222    0.2732     0.000    0.964     0.036      0  0.465590   
964  -0.026667    0.2960     0.000    0.937     0.062      0  0.465596   
1044 -0.100000    0.0000     0.000    1.000     0.000      0  0.465601   
...        ...       ...       ...      ...       ...    ...       ...   
396   0.165832    1.0000     0.021    0.842     0.137      0  0.539171   
258   0.206725    0.9779     0.037    0.788     0.175      0  0.606435   
219   0.024342    0.9863     0.000    0.883     0.117      0  0.606487   
251   0.107384    0.9721     0.049    0.840     0.111      0  0.622133   
189   0.119610   -0.7906     0.065    0.895     0.039      0  0.623944   

       Oppgang  
547   0.534440  
435   0.534430  
570   0.534410  
964   0.534404  
1044  0.534399  
...        ...  
396   0.460829  
258   0.393565  
219   0.393513  
251   0.377867  
189   0.376056  

[1141 rows x 14 columns]

In [51]:
#Create and train the model (KNN)
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 34)
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=34)

In [52]:
knn_score = knn.score(x_test, y_test)
print("Results for KNN Classifier:")
print(knn_score)

Results for KNN Classifier:
0.5013146362839614


In [53]:
y_pred_knn = knn.predict(x_test)

In [54]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix
cm_knn = confusion_matrix(y_test, y_pred_knn)

In [55]:
tn, fp, fn, tp = confusion_matrix(y_test, y_pred_knn).ravel()
print(tn, fp, fn, tp)

287 274 295 285


In [56]:
tpr_knn = round(tp/(tp + fn), 4)
tnr_knn = round(tn/(tn + fp), 4)

In [57]:
print(tpr_knn, tnr_knn)

0.4914 0.5116


In [58]:
#Sjekker sannsynligheten for oppgang og nedgang
KNN = knn.predict_proba(x_test)

In [59]:
predictions_KNN = knn.predict(x_test)
predictions_KNN

array([0, 0, 1, ..., 0, 1, 0])

In [60]:
#Show the model metrics
print( classification_report(y_test, predictions_KNN))

              precision    recall  f1-score   support

           0       0.49      0.51      0.50       561
           1       0.51      0.49      0.50       580

    accuracy                           0.50      1141
   macro avg       0.50      0.50      0.50      1141
weighted avg       0.50      0.50      0.50      1141



In [61]:
KNN

array([[0.5       , 0.5       ],
       [0.58823529, 0.41176471],
       [0.41176471, 0.58823529],
       ...,
       [0.67647059, 0.32352941],
       [0.38235294, 0.61764706],
       [0.5       , 0.5       ]])

In [62]:
column_values_KNN = ["Nedgang-KNN", "Oppgang-KNN"]

df5 = pd.DataFrame(data = KNN,
                  columns = column_values_KNN)

In [63]:
df5

Nedgang-KNN  Oppgang-KNN
0        0.500000     0.500000
1        0.588235     0.411765
2        0.411765     0.588235
3        0.558824     0.441176
4        0.382353     0.617647
...           ...          ...
1136     0.588235     0.411765
1137     0.470588     0.529412
1138     0.676471     0.323529
1139     0.382353     0.617647
1140     0.500000     0.500000

[1141 rows x 2 columns]

In [64]:
extracted_col_KNN = df5["Nedgang-KNN"]
extracted_col_KNN

0       0.500000
1       0.588235
2       0.411765
3       0.558824
4       0.382353
          ...   
1136    0.588235
1137    0.470588
1138    0.676471
1139    0.382353
1140    0.500000
Name: Nedgang-KNN, Length: 1141, dtype: float64

In [65]:
df1 = df1.join(extracted_col_KNN)
df1

Open          Low         High    Volume        Close  \
0     1680.000000  1641.500000  1692.119995   5271300  1658.380005   
1     1638.000000  1585.000000  1642.569946   6367200  1591.910034   
2     1566.000000  1505.010010  1576.130005   8829800  1520.910034   
3     1540.000000  1523.010010  1567.550049   6523000  1551.479980   
4     1543.050049  1483.180054  1584.530029   8792200  1495.079956   
...           ...          ...          ...       ...          ...   
1136    44.402000    43.520000    44.644001  38971500    44.166000   
1137    44.560001    43.644001    45.080002  32795000    44.430000   
1138    43.993999    42.200001    44.234001  42693000    42.279999   
1139    42.720001    42.307999    43.004002  25259500    43.000000   
1140    42.737999    42.462002    43.450001  16127500    43.118000   

      Subjectivity  Polarity  Compound  Negative  Neutral  Positive  Label  \
0         0.570661  0.230603    0.9882     0.053    0.815     0.132      0   
1         0.488820  0.162102    0.9979     0.042    0.782     0.176      0   
2         0.436101  0.173839    0.9964     0.040    0.800     0.159      0   
3         0.479953  0.195635    0.9401     0.088    0.752     0.160      1   
4         0.323829  0.035114   -0.8860     0.123    0.786     0.091      0   
...            ...       ...       ...       ...      ...       ...    ...   
1136      0.427273  0.268182   -0.7650     0.167    0.833     0.000      0   
1137      0.405637  0.059591    0.9954     0.053    0.806     0.141      0   
1138      0.463922  0.001857    0.9678     0.056    0.854     0.089      0   
1139      0.426042  0.218750   -0.6124     0.044    0.947     0.009      1   
1140      0.454072  0.102247    0.9994     0.036    0.865     0.100      1   

       Nedgang   Oppgang  Nedgang-KNN  
0     0.468092  0.531908     0.500000  
1     0.467969  0.532031     0.588235  
2     0.467683  0.532317     0.411765  
3     0.467972  0.532028     0.558824  
4     0.467694  0.532306     0.382353  
...        ...       ...          ...  
1136  0.465833  0.534167     0.588235  
1137  0.466112  0.533888     0.470588  
1138  0.465719  0.534281     0.676471  
1139  0.466601  0.533399     0.382353  
1140  0.467414  0.532586     0.500000  

[1141 rows x 15 columns]

In [66]:
extracted_col1_KNN = df5["Oppgang-KNN"]
extracted_col1_KNN

0       0.500000
1       0.411765
2       0.588235
3       0.441176
4       0.617647
          ...   
1136    0.411765
1137    0.529412
1138    0.323529
1139    0.617647
1140    0.500000
Name: Oppgang-KNN, Length: 1141, dtype: float64

In [67]:
df1 = df1.join(extracted_col1_KNN)
df1

Open          Low         High    Volume        Close  \
0     1680.000000  1641.500000  1692.119995   5271300  1658.380005   
1     1638.000000  1585.000000  1642.569946   6367200  1591.910034   
2     1566.000000  1505.010010  1576.130005   8829800  1520.910034   
3     1540.000000  1523.010010  1567.550049   6523000  1551.479980   
4     1543.050049  1483.180054  1584.530029   8792200  1495.079956   
...           ...          ...          ...       ...          ...   
1136    44.402000    43.520000    44.644001  38971500    44.166000   
1137    44.560001    43.644001    45.080002  32795000    44.430000   
1138    43.993999    42.200001    44.234001  42693000    42.279999   
1139    42.720001    42.307999    43.004002  25259500    43.000000   
1140    42.737999    42.462002    43.450001  16127500    43.118000   

      Subjectivity  Polarity  Compound  Negative  Neutral  Positive  Label  \
0         0.570661  0.230603    0.9882     0.053    0.815     0.132      0   
1         0.488820  0.162102    0.9979     0.042    0.782     0.176      0   
2         0.436101  0.173839    0.9964     0.040    0.800     0.159      0   
3         0.479953  0.195635    0.9401     0.088    0.752     0.160      1   
4         0.323829  0.035114   -0.8860     0.123    0.786     0.091      0   
...            ...       ...       ...       ...      ...       ...    ...   
1136      0.427273  0.268182   -0.7650     0.167    0.833     0.000      0   
1137      0.405637  0.059591    0.9954     0.053    0.806     0.141      0   
1138      0.463922  0.001857    0.9678     0.056    0.854     0.089      0   
1139      0.426042  0.218750   -0.6124     0.044    0.947     0.009      1   
1140      0.454072  0.102247    0.9994     0.036    0.865     0.100      1   

       Nedgang   Oppgang  Nedgang-KNN  Oppgang-KNN  
0     0.468092  0.531908     0.500000     0.500000  
1     0.467969  0.532031     0.588235     0.411765  
2     0.467683  0.532317     0.411765     0.588235  
3     0.467972  0.532028     0.558824     0.441176  
4     0.467694  0.532306     0.382353     0.617647  
...        ...       ...          ...          ...  
1136  0.465833  0.534167     0.588235     0.411765  
1137  0.466112  0.533888     0.470588     0.529412  
1138  0.465719  0.534281     0.676471     0.323529  
1139  0.466601  0.533399     0.382353     0.617647  
1140  0.467414  0.532586     0.500000     0.500000  

[1141 rows x 16 columns]

In [68]:
df1.head(60)

Open          Low         High    Volume        Close  \
0   1680.000000  1641.500000  1692.119995   5271300  1658.380005   
1   1638.000000  1585.000000  1642.569946   6367200  1591.910034   
2   1566.000000  1505.010010  1576.130005   8829800  1520.910034   
3   1540.000000  1523.010010  1567.550049   6523000  1551.479980   
4   1543.050049  1483.180054  1584.530029   8792200  1495.079956   
5   1484.000000  1432.689941  1509.500000   9991800  1460.829956   
6   1464.989990  1363.959961  1480.000000  13640300  1377.449951   
7   1346.000000  1307.000000  1396.030029   7220000  1343.959961   
8   1368.890015  1363.010010  1473.160034  10411800  1470.900024   
9   1454.199951  1390.310059  1469.000000   9722000  1461.640015   
10  1473.349976  1449.000000  1513.469971   8829000  1478.020020   
11  1510.800049  1487.000000  1520.760010   6954500  1501.969971   
12  1465.199951  1460.930054  1553.359985   7983100  1539.130005   
13  1520.010010  1497.109985  1538.000000   6975600  1500.280029   
14  1530.000000  1518.310059  1594.000000   9182600  1575.390015   
15  1602.310059  1589.189941  1634.560059   7993200  1629.510010   
16  1664.689941  1616.609985  1676.609985   8881400  1656.579956   
17  1652.979980  1641.400024  1667.800049   6348800  1659.420044   
18  1641.010010  1621.619995  1663.250000   6507700  1656.219971   
19  1640.550049  1636.219971  1660.290039   4686200  1640.560059   
20  1615.000000  1595.150024  1648.199951   6005900  1617.209961   
21  1632.000000  1626.010010  1675.160034   5998500  1674.560059   
22  1684.219971  1675.880005  1705.000000   6366900  1683.780029   
23  1680.000000  1677.500000  1700.170044   4208900  1693.219971   
24  1712.000000  1691.540039  1716.199951   6020500  1696.199951   
25  1681.000000  1610.199951  1681.869995   6416800  1632.170044   
26  1656.000000  1612.000000  1657.430054   5225200  1640.020020   
27  1641.069946  1631.780029  1657.260010   4089900  1654.930054   
28  1670.500000  1661.609985  1683.479980   4945900  1670.569946   
29  1643.589966  1614.089966  1645.000000   4837700  1637.890015   
30  1631.270020  1590.719971  1632.380005   4632800  1593.880005   
31  1623.000000  1619.680054  1676.949951   5783800  1670.430054   
32  1692.849976  1679.079956  1736.410034  10910300  1718.729980   
33  1638.880005  1622.010010  1673.060059  11506200  1626.229980   
34  1623.000000  1613.500000  1649.630005   4929100  1633.310059   
35  1643.339966  1642.500000  1665.260010   4453100  1658.810059   
36  1670.750000  1633.339966  1672.260010   3939900  1640.260010   
37  1625.000000  1592.910034  1625.540039   4626600  1614.369995   
38  1600.979980  1586.000000  1609.290039   3317300  1591.000000   
39  1604.000000  1598.880005  1639.400024   4858600  1638.010010   
40  1647.000000  1637.109985  1656.380005   3560300  1640.000000   
41  1624.500000  1606.060059  1637.900024   4120500  1622.650024   
42  1627.859985  1604.500000  1628.910034   4343900  1607.949951   
43  1601.000000  1600.560059  1634.000000   3681700  1627.579956   
44  1630.000000  1610.119995  1634.930054   3337600  1622.099976   
45  1619.849976  1600.910034  1623.560059   3483400  1619.439941   
46  1623.500000  1621.170044  1634.939941   3096200  1631.560059   
47  1641.449951  1630.390015  1654.599976   3184500  1633.000000   
48  1625.979980  1616.130005  1639.989990   2665800  1636.400024   
49  1628.180054  1615.099976  1641.810059   3148800  1641.089966   
50  1635.250000  1633.829956  1651.770020   3025900  1639.829956   
51  1655.130005  1651.000000  1674.260010   4974900  1671.729980   
52  1685.000000  1674.359985  1709.430054   6167400  1696.170044   
53  1702.949951  1689.010010  1707.800049   3681500  1692.430054   
54  1695.969971  1668.280029  1697.750000   3996000  1668.949951   
55  1667.369995  1620.510010  1669.750000   4957000  1625.949951   
56  1604.010010  1586.569946  1622.719971   4667000  1620.800049   
57  1626.119995  1626.010010  1672.290039   3876400  1670.619995   

In [69]:
df1.to_csv("Alle6OppgangNedgangUnik-KNN")